-- MySQL Script generated by MySQL Workbench
-- Fri Aug  5 16:23:00 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema demoday
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema demoday
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demoday` DEFAULT CHARACTER SET utf8 ;
USE `demoday` ;

-- -----------------------------------------------------
-- Table `demoday`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `demoday`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`organization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `createTime` TIMESTAMP NULL,
  `modifyTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  `modifyUser` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`contest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`contest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `organizationId` INT NOT NULL,
  `description` TEXT NULL,
  `startDate` DATETIME NULL,
  `endDate` DATETIME NULL,
  `status` INT NULL,
  `active` CHAR(1) NULL DEFAULT 'Y',
  `createTime` TIMESTAMP NULL,
  `modifyTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  `modifyUser` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contest_organization1_idx` (`organizationId` ASC),
  CONSTRAINT `fk_contest_organization1`
    FOREIGN KEY (`organizationId`)
    REFERENCES `demoday`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`topic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contestId` INT NOT NULL,
  `name` VARCHAR(500) NULL,
  `active` CHAR(1) NULL DEFAULT 'Y',
  `createTime` TIMESTAMP NULL,
  `modifyTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  `modifyUser` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_topic_contest1_idx` (`contestId` ASC),
  CONSTRAINT `fk_topic_contest1`
    FOREIGN KEY (`contestId`)
    REFERENCES `demoday`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`contest_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`contest_company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contestId` INT NOT NULL,
  `companyId` INT NULL,
  `topicId` INT GENERATED ALWAYS AS (),
  `organizationId` INT NULL,
  `name` VARCHAR(500) NULL,
  `round` INT NULL,
  `location` VARCHAR(100) NULL,
  `brief` TEXT NULL,
  `fundedDate` DATETIME NULL,
  `teamSize` INT NULL,
  `company` TEXT NULL,
  `joinStatus` INT NULL,
  `sort` INT NULL,
  `createTime` TIMESTAMP NULL,
  `modifyTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  `modifyUser` INT NULL,
  `source` INT NULL,
  `sourceId` VARCHAR(100) NULL,
  `extra` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_demoday_company_company1_idx` (`companyId` ASC),
  INDEX `fk_demoday_company_organization1_idx` (`organizationId` ASC),
  INDEX `fk_demoday_company_topic1_idx` (`topicId` ASC),
  INDEX `fk_contest_company_contest1_idx` (`contestId` ASC),
  CONSTRAINT `fk_demoday_company_company1`
    FOREIGN KEY (`companyId`)
    REFERENCES `demoday`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_demoday_company_organization1`
    FOREIGN KEY (`organizationId`)
    REFERENCES `demoday`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_demoday_company_topic1`
    FOREIGN KEY (`topicId`)
    REFERENCES `demoday`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contest_company_contest1`
    FOREIGN KEY (`contestId`)
    REFERENCES `demoday`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `demoday`.`contest_organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`contest_organization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contestId` INT NOT NULL,
  `organizationId` INT NOT NULL,
  `role` INT NULL,
  `joinStatus` INT NULL,
  `createTime` TIMESTAMP NULL,
  `modifyTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  `modifyUser` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contest_organization_organization1_idx` (`organizationId` ASC),
  INDEX `fk_contest_organization_contest1_idx` (`contestId` ASC),
  UNIQUE INDEX `uq_contest_organization_contestId_organizationId` (`organizationId` ASC, `contestId` ASC),
  CONSTRAINT `fk_contest_organization_organization1`
    FOREIGN KEY (`organizationId`)
    REFERENCES `demoday`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contest_organization_contest1`
    FOREIGN KEY (`contestId`)
    REFERENCES `demoday`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`stage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NULL,
  `contestId` INT NOT NULL,
  `description` TEXT NULL,
  `sort` INT NOT NULL,
  `type` INT NULL,
  `status` INT NULL,
  `nextNum` INT NULL,
  `startDate` DATETIME NULL,
  `endDate` DATETIME NULL,
  `showNext` CHAR(1) NULL DEFAULT 'Y',
  `createTime` TIMESTAMP NULL,
  `modifyTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  `modifyUser` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stage_contest1_idx` (`contestId` ASC),
  CONSTRAINT `fk_stage_contest1`
    FOREIGN KEY (`contestId`)
    REFERENCES `demoday`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`stage_score_dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`stage_score_dimension` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stageId` INT NOT NULL,
  `name` VARCHAR(500) NULL,
  `description` TEXT NULL,
  `weight` INT NULL,
  `minScore` INT NULL,
  `maxScore` INT NULL,
  `modifyUser` INT NULL,
  `sort` INT NULL,
  `createTime` TIMESTAMP NULL,
  `modifyTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dimension_expand_contest_stage1_idx` (`stageId` ASC),
  CONSTRAINT `fk_dimension_expand_contest_stage1`
    FOREIGN KEY (`stageId`)
    REFERENCES `demoday`.`stage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`contest_company_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`contest_company_score` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contestCompanyId` INT NOT NULL,
  `stageScoreDimensionId` INT NOT NULL,
  `userId` INT NOT NULL,
  `score` INT NULL,
  `reason` TEXT NULL,
  `createTime` TIMESTAMP NULL,
  `modifyTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  `modifyUser` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contest_stage_score_user1_idx` (`userId` ASC),
  INDEX `fk_contest_stage_score_contest_company1_idx` (`contestCompanyId` ASC),
  INDEX `fk_contest_stage_score_stage_score_dimension1_idx` (`stageScoreDimensionId` ASC),
  UNIQUE INDEX `unq_content_company_score1` (`contestCompanyId` ASC, `stageScoreDimensionId` ASC, `userId` ASC),
  CONSTRAINT `fk_contest_stage_score_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `demoday`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contest_stage_score_contest_company1`
    FOREIGN KEY (`contestCompanyId`)
    REFERENCES `demoday`.`contest_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contest_stage_score_stage_score_dimension1`
    FOREIGN KEY (`stageScoreDimensionId`)
    REFERENCES `demoday`.`stage_score_dimension` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`contest_company_stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`contest_company_stage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stageId` INT NOT NULL,
  `contestCompanyId` INT NOT NULL,
  `score` FLOAT NULL,
  `status` INT NULL,
  `createTime` TIMESTAMP NULL,
  `modifyTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  `modifyUser` INT NULL,
  `scored` CHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`id`),
  INDEX `fk_state_company_stage1_idx` (`stageId` ASC),
  INDEX `fk_state_company_contest_company1_idx` (`contestCompanyId` ASC),
  UNIQUE INDEX `unq_content_company_stage1` (`stageId` ASC, `contestCompanyId` ASC),
  CONSTRAINT `fk_state_company_stage1`
    FOREIGN KEY (`stageId`)
    REFERENCES `demoday`.`stage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_state_company_contest_company1`
    FOREIGN KEY (`contestCompanyId`)
    REFERENCES `demoday`.`contest_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`stage_user_rel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`stage_user_rel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `stageId` INT NOT NULL,
  `createTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  `modifyTime` TIMESTAMP NULL,
  `modifyUser` INT NULL,
  `canScore` CHAR(1) NULL,
  `canJudge` CHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stage_user_rel_user1_idx` (`userId` ASC),
  INDEX `fk_stage_user_rel_stage1_idx` (`stageId` ASC),
  CONSTRAINT `fk_stage_user_rel_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `demoday`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stage_user_rel_stage1`
    FOREIGN KEY (`stageId`)
    REFERENCES `demoday`.`stage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`content_organization_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`content_organization_topic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contestOrganizationId` INT NOT NULL,
  `topicId` INT NULL,
  `createTime` TIMESTAMP NULL,
  `modifyTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  `modifyUser` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_content_organization_topic_contest_organization1_idx` (`contestOrganizationId` ASC),
  INDEX `fk_content_organization_topic_topic1_idx` (`topicId` ASC),
  CONSTRAINT `fk_content_organization_topic_contest_organization1`
    FOREIGN KEY (`contestOrganizationId`)
    REFERENCES `demoday`.`contest_organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_content_organization_topic_topic1`
    FOREIGN KEY (`topicId`)
    REFERENCES `demoday`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`contest_company_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`contest_company_file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contestCompanyId` INT NOT NULL,
  `name` VARCHAR(500) NOT NULL,
  `file` VARCHAR(100) NOT NULL,
  `createTime` DATETIME NULL,
  `modifyTime` DATETIME NULL,
  `createUser` INT NULL,
  `modifyUser` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contest_company_file_contest_company1_idx` (`contestCompanyId` ASC),
  CONSTRAINT `fk_contest_company_file_contest_company1`
    FOREIGN KEY (`contestCompanyId`)
    REFERENCES `demoday`.`contest_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`contest_company_user_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`contest_company_user_result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contestCompanyId` INT NOT NULL,
  `userId` INT NOT NULL,
  `result` INT NULL,
  `createTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  `modifyTime` TIMESTAMP NULL,
  `modifyUser` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contest_company_user_rel_contest_company1_idx` (`contestCompanyId` ASC),
  INDEX `fk_contest_company_user_rel_user1_idx` (`userId` ASC),
  INDEX `uq_contest_company_user_result_userId_contestCompanyId` (`contestCompanyId` ASC, `userId` ASC),
  CONSTRAINT `fk_contest_company_user_rel_contest_company1`
    FOREIGN KEY (`contestCompanyId`)
    REFERENCES `demoday`.`contest_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contest_company_user_rel_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `demoday`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`contest_company_organization_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`contest_company_organization_result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contestCompanyId` INT NOT NULL,
  `organizationId` INT NOT NULL,
  `result` INT NULL,
  `createTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  `modifyTime` TIMESTAMP NULL,
  `modifyUser` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contest_company_organization_result_contest_company1_idx` (`contestCompanyId` ASC),
  INDEX `fk_contest_company_organization_result_organization1_idx` (`organizationId` ASC),
  UNIQUE INDEX `uq_contest_compamy_org_result_orgId_contestCompayId` (`organizationId` ASC, `contestCompanyId` ASC),
  CONSTRAINT `fk_contest_company_organization_result_contest_company1`
    FOREIGN KEY (`contestCompanyId`)
    REFERENCES `demoday`.`contest_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contest_company_organization_result_organization1`
    FOREIGN KEY (`organizationId`)
    REFERENCES `demoday`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demoday`.`stage_contest_company_user_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`stage_contest_company_user_comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stageId` INT NOT NULL,
  `userId` INT NOT NULL,
  `contestCompanyId` INT NOT NULL,
  `comment` TEXT NULL,
  `createTime` TIMESTAMP NULL,
  `modifyTime` TIMESTAMP NULL,
  `createUser` INT NULL,
  `modifyUser` INT NULL,
  INDEX `fk_stage_contest_company_user_comment_stage1_idx` (`stageId` ASC),
  INDEX `fk_stage_contest_company_user_comment_user1_idx` (`userId` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_stage_contest_company_user_comment_contest_company1_idx` (`contestCompanyId` ASC),
  CONSTRAINT `fk_stage_contest_company_user_comment_stage1`
    FOREIGN KEY (`stageId`)
    REFERENCES `demoday`.`stage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stage_contest_company_user_comment_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `demoday`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stage_contest_company_user_comment_contest_company1`
    FOREIGN KEY (`contestCompanyId`)
    REFERENCES `demoday`.`contest_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `demoday` ;

-- -----------------------------------------------------
-- Placeholder table for view `demoday`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoday`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `demoday`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demoday`.`view1`;
USE `demoday`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
