-- MySQL Script generated by MySQL Workbench
-- Wed Aug 10 13:40:32 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`track` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`track_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`track_topic` (
  `id` INT NOT NULL,
  `type` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscription` (
  `id` INT NOT NULL,
  `userId` INT NOT NULL,
  `topicId` INT NOT NULL,
  `companyId` INT NULL,
  `tagId` INT NULL,
  `createTime` TIMESTAMP NULL,
  `modifyTime` TIMESTAMP NULL,
  `verify` VARCHAR(1) NULL,
  `active` VARCHAR(1) NULL DEFAULT 'Y',
  PRIMARY KEY (`id`),
  INDEX `fk_subscription_user1_idx` (`userId` ASC),
  INDEX `fk_subscription_company1_idx` (`companyId` ASC),
  INDEX `fk_subscription_topic1_idx` (`topicId` ASC),
  INDEX `fk_subscription_tag1_idx` (`tagId` ASC),
  CONSTRAINT `fk_subscription_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscription_company1`
    FOREIGN KEY (`companyId`)
    REFERENCES `mydb`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscription_topic1`
    FOREIGN KEY (`topicId`)
    REFERENCES `mydb`.`track_topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscription_tag1`
    FOREIGN KEY (`tagId`)
    REFERENCES `mydb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`track_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`track_message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `topic_id` INT NOT NULL,
  `company_id` INT NULL,
  `tag_id` INT NULL,
  `abstract` TEXT NULL,
  `description` TEXT NULL,
  `createTime` TIMESTAMP NOT NULL,
  `modifyTime` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_track_message_company1_idx` (`company_id` ASC),
  INDEX `fk_track_message_topic1_idx` (`topic_id` ASC),
  INDEX `fk_track_message_tag1_idx` (`tag_id` ASC),
  CONSTRAINT `fk_track_message_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_track_message_topic1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `mydb`.`track_topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_track_message_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
